questions = [[["Qual o número entre 22 e 24 ?", "28", "23", "46", "22",2],
    ["Quantos lados de mesmo tamanho tem um triângulo equilátero?", "0", "1", "2", "3",4],
    ["Quanto é 22 dividido por 2?", "2", "10", "11", "1",3],
    ["Qual é o formato que possuí apenas 3 lados?", "Triângulo", "Quadrado", "Círculo", "Trapézio",1],
    ["Quanto é 25 dividido por 5?","15", "20", "10", "5",4],
    ["Quanto é 3 multiplicado por 4?", "7", "12", "4", "2", 2],
    ["Se dividirmos 8 bolos para quatro pessoas, cada um ganha quantos bolos?", "½ ", "2", "4", "1",2],
    ["Qual o nome da figura geométrica de  quatro lados?", "Quadrilátero", "Círculo", "Triângulo", "Prisma",1],
    ["Quanto é 41 -26?", "20","15", "1", "0",2],
    ["Qual o nome da operação em que se diminui uma quantidade da outra?", "Adição", "Divisão", "Multiplicação", "Subtração",4],
    ["Qual o nome da operação  que consiste em somar o mesmo número várias vezes ?", "Subtração", "Divisão", "Adição", "Multiplicação",4],
    ["Qual o nome da operação em que se soma dois números?", "Adição", "Divisão", "Multiplicação", "Subtração",1],
    ["Qual destes não é um quadrilátero?", "Trapézio", "Retângulo", "Pentágono", "Quadrado",3], 
    ["Qual o nome da figura geométrica sem nenhum lado?", "Círculo", "Quadrado", "Triângulo", "Semi-círculo",1],
    ["Qual das seguintes sequências está em ordem crescente?", "2,1,3", "1,2,3", "3,1,2", "3,2,1",2],
    ["Qual das seguintes sequências está em ordem decrescente?", "3,1,2", "2,1,3", "1,2,3", "3,2,1",4],
    ["Se tenho 6 amigos e quero dar 4 chocolates para cada, de quantos chocolates preciso?", "18", "6", "12", "24",4],
    ["Quantos sapatos 8 pessoas precisam para calçar todos os pés?", "8", "16", "10", "4",2],
    ["Se consigo fazer 2 desenhos com um lápis, de quantos lápis preciso no mínimo para fazer 11 desenhos ?", "6", "5", "3", "2",1],
    ["Em um jogo de celular consigo fazer 15 pontos em 10 minutos, quantos pontos faço em 30 minutos?", "20", "45", "35", "20",2],
    ["Quanto é 8x7?", "36", "49", "64", "56",4],
    ["Quanto é 10x10-23", "77", "67", "80", "0",1],
    ["Qual o maior número que é possível criar com os algarismos ‘7’, ‘9’, ‘3’, e ‘2’?", "2973", "7923", "9732", "9237",3],
    ["Fui para uma lanchonete com 10 reais, comprei um salgado de 4 reais e um suco de 2 reais, quanto sobrou?", "4", "6", "10", "2",1],
    ["Qual dessas operações resulta em 52?", "18+12", "21-11", "4x30", "20+32",4],
    ["Qual dessas operações resulta em 100?", "49+51", "100/10", "100-1", "10+0",1],
    ["Qual dessas operações resulta em 27?", "16x1", "30-4", "27x1", "15+10",3],
    ["Qual dessas operações resulta em 0?", "3x5-10", "10+2", "35-20-15", "20/2",3],
    ["Qual dessas operações resulta em 70?","15x4", "10x10", "100-29", "35x2",4],
    ["Qual fração representa 0,25?", "¼ ", "⅕ ", "⅙ ", "½ ",1],
    ["Represente  ¼ em número decimal?", "0,1", "0,5", "0,1",  "0,25",4],
    ["Quantos lados de mesmo tamanho tem um triângulo escaleno?", "0", "1", "2", "3",1],
    ["Quantos lados de mesmo tamanho tem um triângulo isóceles?", "0", "1", "2", "3",3],
    ["Qual número que subtraído por 3 resulta em 7?", "2", "10", "7", "4",2],
    ["Qual número que ao adicionar 4 resulta em 10?", "8", "5", "3", "6",4],
    ["Se um vídeogame custa 200 reais, quantos videogames posso comprar com 1000 reais?", "1", "3", "5", "10",3],
    ["Qual numero completa a seguinte sequência de números crescentes “1,2,_,4,5,6 ?", "6", "4", "3", "8",3],
    ["Qual numero completa a seguinte sequência de números decrescentes ”6,5,4,3,_,1?", "1", "3", "4", "2",4],
    ["Se consigo fazer um bolo em 3 horas, quantos bolos consigo fazer em um dia?", "3", "6", "8", "2",3],
    ["Qual é o dobro do número 4 ?", "16", "5", "6",  "8",4],
    ["Qual é a metade do número 4 ?", "8", "2", "5",  "16",2],
    ["Preencha o número que falta na operação: 20 + _ = 26?", "11", "3", "4", "6",4],
    ["Preencha o número que falta na operação: 52 - _ = 31?", "21", "4", "9", "2", 1],
    ["Preencha o número que falta na operação: 8 - _ = 1?", "7", "6", "2", "0",1],
    ["Preencha o número que falta na operação: 40 / _ = 4?", "5", "4", "10", "2",3],
    ["Preencha o número que falta na operação: 5 x _ = 30 ?", "10", "2", "1", "6",4],
    ["Qualquer número multiplicado por ? sempre resulta nele mesmo.?", "4", "0", "1", "3",3],
    ["Qualquer número multiplicado por ? sempre resulta em zero?", "3", "1", "0", "10",3],
    ["Quantas casas decimais existem no número 144?", "1", "2", "3", "4",3],
    ["Qual o nome da operação em que se reparte uma quantidade em porções menores iguais?", "Divisão", "Adição", "Multiplicação", "Subtração",1]],
    [
        ["Quem descobriu o Brasil?", "Cristóvão Colombo", "Pedro Álvares Cabral", "Fernão Mendes Pinto", "Vasco da Gama", 2],
    ["Em que ano o Brasil se tornou independente de Portugal?", "1500", "1822", "1889", "1964", 2],
    ["Quem foi o imperador do Brasil quando ele se tornou independente?", "Dom João VI", "Dom Pedro I", "Dom Pedro II", "Dom Manuel I", 2],
    ["O que aconteceu no 7 de setembro de 1822?", "Descobrimento do Brasil", "Proclamação da República", "Independência do Brasil", "Chegada da Família Real ao Brasil", 3],
    ["Em que ano a escravidão foi oficialmente abolida no Brasil?", "1500", "1822", "1888", "1964", 3],
    ["Qual foi o nome do último imperador do Brasil?", "Dom Pedro II", "Dom Pedro I", "Dom João VI", "Dom Manuel I", 1],
    ["Quem foi o líder da Inconfidência Mineira?", "Tiradentes", "Dom Pedro II", "José Bonifácio", "Zumbi dos Palmares", 1],
    ["Qual foi o nome do movimento que buscava a abolição da escravidão no Brasil?", "Inconfidência Mineira", "Cabanagem", "Abolicionismo", "Confederação do Equador", 3],
    ["Em que ano foi proclamada a República no Brasil?", "1500", "1822", "1889", "1964", 3],
    ["Quem foi a primeira presidente mulher do Brasil?", "Dilma Rousseff", "Juscelino Kubitschek", "Fernando Collor", "Getúlio Vargas", 1],
    ["Qual é o nome da bandeira do Brasil?", "Bandeira Verde e Amarela", "Bandeira Azul e Branca", "Bandeira Vermelha e Preta", "Bandeira Vermelha e Branca", 1],
    ["Qual é a capital do Brasil?", "Rio de Janeiro", "São Paulo", "Brasília", "Belo Horizonte", 3],
    ["Quem foi o líder do movimento dos caras-pintadas?", "Fernando Collor", "Luiz Inácio Lula da Silva", "Jair Bolsonaro", "Tancredo Neves", 2],
    ["Onde fica o Cristo Redentor, uma das Sete Maravilhas do Mundo Moderno?", "Rio de Janeiro", "São Paulo", "Brasília", "Belo Horizonte", 1],
    ["Qual é o maior rio do Brasil?", "Rio Amazonas", "Rio Paraná", "Rio São Francisco", "Rio Tietê", 1],
    ["Quem foi o presidente do Brasil durante a Copa do Mundo de 2014?", "Dilma Rousseff", "Luiz Inácio Lula da Silva", "Jair Bolsonaro", "Michel Temer", 1],
    ["Qual é o nome do símbolo da bandeira do Brasil?", "Cruzeiro do Sul", "Estrela do Norte", "Estrela de Davi", "Círculo Estrelado", 1],
    ["Quem foi o líder militar e político da independência do Brasil?", "Dom Pedro I", "Dom Pedro II", "Dom João VI", "Dom Manuel I", 1],
    ["O que é o Samba?", "Comida típica brasileira", "Estilo musical e de dança", "Dança folclórica", "Esporte nacional", 2],
    ["Qual é a capital do estado de São Paulo?", "Rio de Janeiro", "São Paulo", "Brasília", "Belo Horizonte", 2],
    ["Qual é o nome da moeda brasileira?", "Peso", "Dólar", "Real", "Euro", 3],
    ["O que é o Sertanejo?", "Estilo musical", "Prato típico", "Dança folclórica", "Esporte nacional", 1],
    ["Qual é o nome do maior bioma brasileiro, conhecido por sua biodiversidade?", "Pantanal", "Cerrado", "Caatinga", "Amazônia", 4],
    ["O que é o Candomblé?", "Esporte nacional", "Festival cultural", "Estilo musical", "Religião afro-brasileira", 4],
    ["Quem foi a princesa que assinou a Lei Áurea, abolindo a escravidão no Brasil?", "Princesa Isabel", "Princesa Leopoldina", "Princesa Carolina", "Princesa Maria da Glória", 1],
    ["O que é o Forró?", "Esporte nacional", "Festival cultural", "Estilo musical e de dança", "Dança folclórica", 3],
    ["Qual é o nome do prato típico brasileiro preparado com feijão-preto, arroz, carne-seca, linguiça e outros ingredientes?", "Feijoada", "Acarajé", "Coxinha", "Churrasco", 1],
    ["Qual é o nome da festa popular brasileira que ocorre antes do período da Quaresma?", "Réveillon", "Festa Junina", "Oktoberfest", "Carnaval", 4],
    ["O que é a Capoeira?", "Esporte nacional", "Estilo musical e de dança", "Dança folclórica", "Arte marcial afro-brasileira", 4],
    ["Quem foi a rainha do Egito famosa por seu relacionamento com líderes romanos, como Júlio César e Marco Antônio?", "Cleópatra", "Nefertiti", "Hatshepsut", "Isis", 1],
    ["Qual imperador romano ficou conhecido por sua política de Pão e Circo?", "Augusto", "Nero", "Constantino", "Júlio César", 2],
    ["Em que cidade do Egito Antigo se encontra a Grande Pirâmide de Quéops?", "Alexandria", "Tebas", "Mênfis", "Gizé", 4],
    ["Quem foi o líder macedônio que conquistou um vasto império, estendendo-se da Grécia até o Egito e a Índia?", "Pericles", "Alexandre, o Grande", "Sólon", "Aristóteles", 2],
    ["Qual foi o general romano que se tornou ditador vitalício e foi assassinado em um famoso episódio do Senado Romano?", "Marco Antônio", "Júlio César", "Bruto", "Cícero", 2],
    ["Qual era a forma de governo em que um pequeno grupo de pessoas governava a cidade-estado de Atenas?", "Democracia", "Oligarquia", "Monarquia", "Tirania", 2],
    ["Qual foi a civilização que se desenvolveu nas margens do rio Nilo, no nordeste da África?", "Babilônica", "Suméria", "Egípcia", "Persa", 3]]
    ]

# questions = [
#     ["Qual é a capital da França?", "Paris", "Londres", "Berlim", "Roma", 1],
#     ["Qual é o resultado de 8 + 5?", "12", "13", "15", "18", 2],
#     ["Quem pintou a Mona Lisa?", "Picasso", "Da Vinci", "Van Gogh", "Warhol", 2],
#     ["Quanto é 6 multiplicado por 7?", "36", "42", "48", "54", 2],
#     ["Qual é o maior planeta do sistema solar?", "Marte", "Saturno", "Júpiter", "Vênus", 3],
#     ["Quem escreveu a obra 'Dom Quixote'?", "Machado de Assis", "Miguel de Cervantes", "Jorge Luis Borges", "Gabriel García Márquez", 2],
#     ["Qual é a fórmula química da água?", "H2O", "CO2", "NaCl", "CH4", 1],
#     ["Quem foi o primeiro presidente dos Estados Unidos?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John F. Kennedy", 1],
#     ["Qual é o resultado de 4 ao cubo?", "16", "32", "64", "128", 3],
#     ["Qual é a capital da Rússia?", "Moscou", "São Petersburgo", "Kiev", "Varsóvia", 1],
#     ["Quem descobriu a teoria da relatividade?", "Isaac Newton", "Galileu Galilei", "Albert Einstein", "Nikola Tesla", 3],
#     ["Qual é o símbolo químico do ouro?", "Au", "Ag", "Cu", "Fe", 1],
#     ["Quem foi o autor da obra 'Romeu e Julieta'?", "William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen", 1],
#     ["Qual é a capital do Brasil?", "Rio de Janeiro", "Brasília", "São Paulo", "Salvador", 2],
#     ["Qual é o resultado de 9 dividido por 3?", "1", "2", "3", "4", 3],
#     ["Quem pintou a obra 'A Noite Estrelada'?", "Leonardo da Vinci", "Michelangelo", "Salvador Dalí", "Vincent van Gogh", 4],
#     ["Qual é o maior oceano do mundo?", "Atlântico", "Índico", "Pacífico", "Ártico", 3],
#     ["Qual é o resultado de 2 elevado a 8?", "8", "16", "64", "256", 4],
#     ["Quem escreveu a obra '1984'?", "George Orwell", "Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald", 1],
#     ["Qual é o resultado de 15 menos 7?", "5", "6", "7", "8", 3],
#     ["Quem foi o pintor do quadro 'A Última Ceia'?", "Pablo Picasso", "Salvador Dalí", "Michelangelo", "Leonardo da Vinci", 4]

# ]