
questao = [
    [
        ["Qual o número entre 22 e 24 ?", "28", "23", "46", "22",2],
        ["Quantos lados de mesmo tamanho tem um triângulo equilátero?", "0", "1", "2", "3",4],
        ["Quanto é 22 dividido por 2?", "2", "10", "11", "1",3],
        ["Qual é o formato que possuí apenas 3 lados?", "Triângulo", "Quadrado", "Círculo", "Trapézio",1],
        ["Quanto é 25 dividido por 5?","15", "20", "10", "5",4],
        ["Quanto é 3 multiplicado por 4?", "7", "12", "4", "2", 2],
        ["Se dividirmos 8 bolos para quatro pessoas, cada um ganha quantos bolos?", "½ ", "2", "4", "1",2],
        ["Qual o nome da figura geométrica de  quatro lados?", "Quadrilátero", "Círculo", "Triângulo", "Prisma",1],
        ["Quanto é 41 -26?", "20","15", "1", "0",2],
        ["Qual o nome da operação em que se diminui uma quantidade da outra?", "Adição", "Divisão", "Multiplicação", "Subtração",4],
        ["Qual o nome da operação  que consiste em somar o mesmo número várias vezes ?", "Subtração", "Divisão", "Adição", "Multiplicação",4],
        ["Qual o nome da operação em que se soma dois números?", "Adição", "Divisão", "Multiplicação", "Subtração",1],
        ["Qual destes não é um quadrilátero?", "Trapézio", "Retângulo", "Pentágono", "Quadrado",3], 
        ["Qual o nome da figura geométrica sem nenhum lado?", "Círculo", "Quadrado", "Triângulo", "Semi-círculo",1],
        ["Qual das seguintes sequências está em ordem crescente?", "2,1,3", "1,2,3", "3,1,2", "3,2,1",2],
        ["Qual das seguintes sequências está em ordem decrescente?", "3,1,2", "2,1,3", "1,2,3", "3,2,1",4],
        ["Se tenho 6 amigos e quero dar 4 chocolates para cada, de quantos chocolates preciso?", "18", "6", "12", "24",4],
        ["Quantos sapatos 8 pessoas precisam para calçar todos os pés?", "8", "16", "10", "4",2],
        ["Se consigo fazer 2 desenhos com um lápis, de quantos lápis preciso no mínimo para fazer 11 desenhos ?", "6", "5", "3", "2",1],
        ["Em um jogo de celular consigo fazer 15 pontos em 10 minutos, quantos pontos faço em 30 minutos?", "20", "45", "35", "20",2],
        ["Quanto é 8x7?", "36", "49", "64", "56",4],
        ["Quanto é 10x10-23", "77", "67", "80", "0",1],
        ["Qual o maior número que é possível criar com os algarismos ‘7’, ‘9’, ‘3’, e ‘2’?", "2973", "7923", "9732", "9237",3],
        ["Fui para uma lanchonete com 10 reais, comprei um salgado de 4 reais e um suco de 2 reais, quanto sobrou?", "4", "6", "10", "2",1],
        ["Qual dessas operações resulta em 52?", "18+12", "21-11", "4x30", "20+32",4],
        ["Qual dessas operações resulta em 100?", "49+51", "100/10", "100-1", "10+0",1],
        ["Qual dessas operações resulta em 27?", "16x1", "30-4", "27x1", "15+10",3],
        ["Qual dessas operações resulta em 0?", "3x5-10", "10+2", "35-20-15", "20/2",3],
        ["Qual dessas operações resulta em 70?","15x4", "10x10", "100-29", "35x2",4],
        ["Quanto é 7x7?", "36", "49", "64", "56",2],
        ["Represente  ¼ em número decimal?", "0,1", "0,5", "0,15",  "0,25",4],
        ["Quantos lados de mesmo tamanho tem um triângulo escaleno?", "0", "1", "2", "3",1],
        ["Quantos lados de mesmo tamanho tem um triângulo isóceles?", "0", "1", "2", "3",3],
        ["Qual número que subtraído por 3 resulta em 7?", "2", "10", "7", "4",2],
        ["Qual número que ao adicionar 4 resulta em 10?", "8", "5", "3", "6",4],
        ["Se um vídeogame custa 200 reais, quantos videogames posso comprar com 1000 reais?", "1", "3", "5", "10",3],
        ["Qual numero completa a seguinte sequência de números crescentes “1,2,_,4,5,6 ?", "6", "4", "3", "8",3],
        ["Qual numero completa a seguinte sequência de números decrescentes ”6,5,4,3,_,1?", "1", "3", "4", "2",4],
        ["Se consigo fazer um bolo em 3 horas, quantos bolos consigo fazer em um dia?", "3", "6", "8", "2",3],
        ["Qual é o dobro do número 4 ?", "16", "5", "6",  "8",4],
        ["Qual é a metade do número 4 ?", "8", "2", "5",  "16",2],
        ["Preencha o número que falta na operação: 20 + _ = 26?", "11", "3", "4", "6",4],
        ["Preencha o número que falta na operação: 52 - _ = 31?", "21", "4", "9", "2", 1],
        ["Preencha o número que falta na operação: 8 - _ = 1?", "7", "6", "2", "0",1],
        ["Preencha o número que falta na operação: 40 / _ = 4?", "5", "4", "10", "2",3],
        ["Preencha o número que falta na operação: 5 x _ = 30 ?", "10", "2", "1", "6",4],
        ["Qualquer número multiplicado por ? sempre resulta nele mesmo.?", "4", "0", "1", "3",3],
        ["Qualquer número multiplicado por ? sempre resulta em zero?", "3", "1", "0", "10",3],
        ["Quantas casas decimais existem no número 144?", "1", "2", "3", "4",3],
        ["Tenho 20 reais e quero comprar um chocolate de 4 reais para 3 amigos, quanto sobra?", "8", "4", "2", "6",1],
        ["Qual o nome da operação em que se reparte uma quantidade em porções menores iguais?", "Divisão", "Adição", "Multiplicação", "Subtração",1]],
        
    [
        ["Qual é a capital do Brasil?", "Rio de Janeiro", "São Paulo", "Brasília", "Belo Horizonte", 3],
        ["Em qual continente fica o Brasil?", "América do Norte", "América do Sul", "África", "Europa", 2],
        ["Qual é a maior cidade do Brasil", "Rio de Janeiro", "São Paulo", "Brasília", "Belo Horizonte", 2],
        ["Qual a floresta mais importante atualmente no Brasil?", "Floresta Atlântica", "Floresta do Congo", "Floresta  do Prado", "Floresta Amazônica", 4],
        ["Quantos oceanos banham o Brasil?", "4", "3", "2", "1", 4],
        ["Qual é a capital da Argentina?", "Buenos Aires", "Montevidéu", "Santiago", "Lima", 1],
        ["Em que país está localizado o Taj Mahal?", "Índia", "China", "Egito", "Turquia", 1],
        ["Qual é a cidade mais populosa do mundo?", "Tóquio", "Nova Delhi", "Xangai", "Cidade do México", 1],
        ["Em que continente está localizado o Deserto do Saara?", "África", "Ásia", "América do Sul", "Austrália", 1],
        ["Qual é a capital do Canadá?", "Toronto", "Ottawa", "Vancouver", "Montreal", 2],
        ["Quais são os dois países mais extensos do mundo em termos de território?", "Rússia e Canadá", "China e Estados Unidos", "Brasil e Índia", "Austrália e Argentina", 1],
        ["Em que oceano está localizado o Triângulo das Bermudas?", "Atlântico Norte", "Pacífico Sul", "Índico", "Ártico", 1],
        ["Qual é a capital da Turquia?", "Istambul", "Ancara", "Izmir", "Anatólia", 2],
        ["Em que continente está localizado o Polo Sul?", "Antártida", "África", "Oceania", "Europa", 1],
        ["Qual é o maior rio da Europa?", "Danúbio", "Reno", "Volga", "Tamisa", 3],
        ["Em que país se encontra a cidade de Marrakech?", "Egito", "Marrocos", "Tunísia", "Argélia", 2],
        ["Qual é o país mais populoso do mundo?", "China", "Índia", "Estados Unidos", "Brasil", 1],
        ["Em que oceano está localizado o Arquipélago do Havaí?", "Atlântico", "Pacífico", "Índico", "Ártico", 2],
        ["Em que cordilheira está localizado o Monte Everest?", "Himalaias", "Andes", "Alpes", "Cordilheira dos Apalaches", 1],
        ["Qual é o deserto mais seco do mundo?", "Saara", "Atacama", "Gobi", "Karakum", 2],
        ["Em que país está localizado o Rio Nilo?", "Nigéria", "Quênia", "Etiópia", "Egito", 4],
        ["Qual é a capital da Austrália?", "Sydney", "Melbourne", "Canberra", "Brisbane", 3],
        ["Qual é a capital da Alemanha?", "Munique", "Berlim", "Hamburgo", "Frankfurt", 2],
        ["Quais são os países que fazem parte da Península Ibérica?", "Espanha e França", "Espanha e Itália", "Portugal e Espanha", "Itália e Portugal", 3],
        ["Qual é o maior lago da África?", "Lago Vitória", "Lago Niassa", "Lago Tanganica", "Lago Malawi", 1],
        ["Em que continente está localizado o Deserto do Atacama?", "África", "Ásia", "América do Sul", "Oceania", 3],
        ["Qual é a capital da Coreia do Sul?", "Pequim", "Seul", "Tóquio", "Bangcoc", 2],
        ["Em que oceano está localizado o Cabo da Boa Esperança?", "Atlântico", "Índico", "Pacífico", "Ártico", 2],
        ["Qual é a capital da Espanha?", "Lisboa", "Madri", "Barcelona", "Valência", 2],
        ["Em que país está localizado o Mar Morto?", "Israel", "Jordânia", "Líbano", "Síria", 2],
        ["Qual é o país mais extenso da América do Sul?", "Argentina", "Brasil", "Colômbia", "Peru", 2],
        ["Em que cordilheira está localizado o Vale da Morte, nos Estados Unidos?", "Montanhas Rochosas", "Serra Nevada", "Cordilheira dos Andes", "Sierra Madre", 2],
        ["Qual é a capital do Japão?", "Seul", "Tóquio", "Xangai", "Osaka", 2],
        ["Os três estados físicos da água são:","Gelo, fogo e ar.","Ebulição, minerais, e pedra.", "Filtração, gasoso e líquido","Sólido, líquido e gasoso.",4],
        ["O movimento que a Terra realiza em torno de seu próprio eixo é chamado de:","Rotação.","Translação.", "Rotatória.","Poluição.",1],
        ["Os alimentos produzidos de forma saudável e que não agridem o meio ambiente são chamados de:", "Agrotóxicos.","Transgênicos.","Industrializados.","Orgânicos",4],
        [" O leite é adquirido de qual atividade?","Extrativismo.","Pecuária.", "Agricultura.","Horticultura.",2],
        ["Onde se localiza a maior parte da água do nosso Planeta?","Rios.","Oceanos.", "Geleiras.","Lagoas.",2],
        ["No ciclo hidrológico, a água circula em quais estados físicos?","Líquido, gasoso e sólido.","Sólido, congelado e líquido.", "Sólido e líquido.","Gasoso, vapor e líquido.",3],
        ["Os mapas podem representar muitos aspectos de nosso dia a dia e de nossas vidas. Qual dos instrumentos abaixo não é utilizado para desenhar um mapa?", "Compasso.", "Ampulheta.", "Esquadro.", "Régua.",1 ],
        ["O mapa é uma representação gráfica e métrica de uma porção de território sobre uma superfície. Como se chama a ciência que estuda e elabora os mapas?", "Geografia", "Cartografia", "Iconografia", "Estatística", 1],
        ["Qual dos conceitos abaixo não faz parte da linguagem cartográfica?", "Símbolos", "Legenda", "Cursos de água", "Escala", 3],
        ["Todos os dias de nossas vidas, necessitamos organizar e nos orientar pelo espaço no qual vivemos, seja na escola, no trabalho ou nas ruas de nossa cidade. Qual dos itens abaixo é um instrumento de localização?", "Cronômetro", "Compasso", "Relógio", "Bússola", 4],
        ["Qual dos elementos abaixo é considerado um ponto cardeal?", "Sudeste", "Centroeste", "Noroeste", "Norte", 4],
        ["O ponto colateral Nordeste encontra-se no meio de quais pontos cardeais?", "Sul e Norte", "Norte e Leste", "Sul e Leste", "Sul e Oeste", 2],
        ["O local onde nasce o Sol, visto da Terra, é no:", "Norte", "Sul", "Leste", "Oeste", 3],
        ["Qual Instrumento é capaz de indicar a localização no espaço através de satélites?", "Bússola", "GPS", "Estrelas", "Mapas", 2],
        ["O Brasil é composto por 5 regiões. Qual delas ocupa a maior área territorial?", "Norte", "Sudeste", "Sul", "Nordeste", 1],
        ["Devido à gravidade da lua, ela exerce influência direta na Terra. Sua força gravitacional consegue mover grandes massas de água, conforme a alteração de suas fases. A lua é considerada:", "Estrela", "Satélite Artificial", "Satélite Natural", "Planeta", 3],
        ["Como são chamadas as pessoas que trabalham nas fábricas em troca de um salário mínimo?", "Empreendedores", "Agrônomos", "Autônomos", "Operários", 4]],
    [
        ["A água e os sais minerais e outros elementos são imprescindíveis para que aconteça a fotossíntese, dentre eles, é necessário:", "o vento", "A pedra", "O fogo.", "A luz solar", 4],
        ["Qual dos gases abaixo é utilizado pelos vegetais na fotossíntese e necessário para a produção do seu próprio alimento?", "Oxigênio", "Gás carbônico", "Hidrogênio", "Nitrogênio", 2],
        ["Qual é o nome do açúcar que fornece energia para o funcionamento das funções das plantas e é produzido pelos vegetais?", "Lactose", "Glicose.", "Brasília", "Quitina", 2],
        ["Durante uma aula de ciências, o professor falou que animais que possuem quatro pernas são chamados de quadrúpedes. Um exemplo desse tipo de bicho é:", "Galo", "Cavalo", "Peixe", "Canguru", 2],
        ["As fases da lua representam os diferentes aspectos que a vemos da terra ao longo de um ciclo. Em média, quantos dias duram cada fase da lua?", "4 a 7", "7 a 8", "14 a 15", "21 a 28", 2],
        ["Devido à gravidade da lua, ela exerce influência direta na Terra. A lua é considerada:", "um satélite natural.", "um satélite artificial", "um cometa", "uma estrela", 1],
        ["Na fotossíntese, os vegetais absorvem o gás ______________ e liberam gás __________. As palavras que completamo trecho são:", "hidrogênio,carbônico.", "carbônico,oxigênio", "oxigênio,nitrogênio.", "nitrogênio,carbônico.", 2],
        ["Ele é um de tipo de carboidrato que está disponível abundantemente na natureza, ocorrendo em quantidade superior à da celulose. Como é chamada essa reserva de glicose dos vegetais?", "Clorofila", "Amido", "Insulina", "Glicogênio", 2],
        ["As plantas, algas, cianobactérias e algumas bactérias realizam fotossíntese e são denominados seres autótrofos ou seres:", "elétrons", "cloroplastos", "carbonos", "clorofilados", 4],
        ["A bolacha-do-mar tem um esqueleto feito de um material chamado carbonato de cálcio, sendo o mesmo das conchas.Ela se alimenta de algas, sendo considerada:", "ser autônomo.", "animal autotrófico", "planta heterotrófica", "animal heterotrófico", 4],
        ["Qual é o órgão responsável pelo bombeamento do sangue no corpo humano?", "Pulmão", "Coração", "Cérebro", "Estômago", 2],
        ["O que é a fotossíntese?", "Respiração de plantas", "Digestão de animais", "Produção de oxigênio", "Queima de calorias", 3],
        ["Qual é o planeta mais próximo do Sol no nosso sistema solar?", "Vênus", "Marte", "Mercúrio", "Júpiter", 3],
        ["O que mantém os planetas em órbita ao redor do Sol?", "Gravidade", "Ímãs", "Força centrífuga", "Vento solar", 1],
        ["Quais são os três estados da matéria?", "Sólido,Líquido,Gasoso", "Líquido,Gasoso,Plasma", "Gasoso,Plasma,Sólido", "Plasma,Sólido,Líquido", 1],
        ["O que é um ecossistema?", "Computador avançado", "Sistema de tráfego", "Coletivo de seres vivos", "Conjunto de órgãos", 3],
        ["Qual é a camada externa da Terra onde vivemos?", "Manto", "Núcleo", "Litosfera", "Atmosfera", 4],
        ["A evaporação é a transformação de:", "água para gelo", "Liquido para gasoso", "Solido para liquido", "Liquido para solido", 2],
        ["Qual é a função principal dos pulmões no sistema respiratório?", "Filtrar o ar", "Produzir oxigênio", "Troca gasosa", "Produzir C02", 3],
        ["O que é um ímã?", "Atrator de metais", "Substância radioativa", "Químico raro", "Mineral transparente", 1],
        ["Qual órgão do corpo humano é atingido pelo alzheimer?", "Bexiga", "Cérebro", "Fígado", "Coração", 3],
        ["Qual é o nome da reação química que libera energia a partir da glicose?", "Fotossíntese", "Respiração celular", "Digestão", "Coagulação sanguínea", 2],
        ["O que é um ecossistema aquático?", "Floresta tropical", "Deserto", "Local imerso em água", "Planalto elevado", 3],
        ["Qual é a principal função dos rins no corpo humano?", "Digestão", "Filtragem do sangue", "Produção de hormônios", "Respiração", 2],
        ["O que é um ecossistema terrestre?", "Local imerso em água", "Floresta tropical", "Deserto", "Planalto elevado", 3],
        ["Qual é o nome da força que atrai objetos em direção ao centro da Terra?", "Força centrífuga", "Força magnética", "Força gravitacional", "Força elétrica", 3],
        ["Como são chamadas as células especiais que formam o cérebro e as outras estruturas do sistema nervoso?", "Neurônios.", "Salivares", "Tecidos.", "Medulas.", 1],
        ["O que é a gravidade?", "Força de movimento", "Força de atração", "Força dos foguetes", "Força magnética", 2],
        ["Qual é a unidade básica de que se forma a  vida?", "Célula", "Átomo", "Molécula", "Gene", 1],
        ["Como são chamados os animais que são criados pelas pessoas em suas casas?", "Domésticos", "Valentes", "Selvagens.", "Parentes", 1],
        ["Qual é o nome do processo de transformação de um gás para o estado líquido?", "Evaporação", "Condensação", "Solidificação", "Sublimação", 2],
        ["Qual é o nome da substância que dá cor às folhas das plantas?", "Clorofila", "Melanina", "Hemoglobina", "Colágeno", 1],
        ["O que expele um vulcão?", "Água", "Gases e magma", "Luz", "Metais", 2],
        ["Qual é o nome do maior órgão do corpo humano?", "Coração", "Pulmão", "Fígado", "Cérebro", 3],
        ["O que é um terremoto?", "Explosão vulcânica", "Choques tectônicos", "Tempestade intensa", "Inundação repentina", 2],
        ["Qual é a função dos pulmões no sistema respiratório?", "Produção de oxigênio", "Respiração", "Produção de CO2", "Digestão de alimentos", 2],
        ["O que é a metamorfose?", "transformação de um gás", "transformação do líquido", "Alteração do ser vivo", "transformação de sólidos", 3],
        ["Qual é o nome da primeira lei de Newton?", "Lei da inércia", "Lei da ação e reação", "Lei da gravidade", "Lei da termodinâmica", 1],
        ["Qual é o nome do processo de transformação de um sólido diretamente para um estado gasoso?", "Evaporação", "Condensação", "Sublimação", "Fusão", 3],
        ["O que são fósseis?", "Restos de animais vivos", "Restos de comida", "Vestígios de seres vivos", "Minerais raros", 3],
        ["Qual é a camada mais externa da atmosfera terrestre?", "Troposfera", "Estratosfera", "Mesosfera", "Exosfera", 4],
        ["O que é a pressão atmosférica?", "Peso do ar na superfície", "Peso de objetos", "Força gravitacional", "Força magnética", 1],
        ["Qual é o nome da reação química que libera luz e calor?", "Fotossíntese", "Combustão", "Respiração celular", "Digestão", 2],
        ["O que é a poluição do ar?", "Excesso de chuvas", "Espalhar ar tóxico", "Queimadas controladas", "Solo nutritivo", 2],
        ["Qual é a função dos cloroplastos nas células vegetais?", "Produção de energia", "Armazenamento nutritivo", "Realização da fotossíntese", "Digestão de alimentos", 3],
        ["O que é um átomo?", "Bola indestrutível", "Pártícula fundamental", "Energia infinita", "Ser unicelular", 2],
        ["Qual é a função dos ossos no corpo humano?", "Produção de sangue", "Sustentação do corpo", "Digestão de alimentos", "Absorção de nutrientes", 2],
        ["Qual destes planetas é rochoso?", "Terra", "Saturno", "Urano", "Sol", 1],
        ["NÃO é um órgão que faz parte do sistema digestório?", "A boca", "A faringe", "O estomago", "O rim", 4],
        ["Qual é a principal importância da digestão para o nosso corpo?", "Eliminar resíduos", "Gerar energia", "Regular o sangue", "Produzir enzimas", 2],
        ["Em um aquário existe um elemento não-vivo, ou seja, abiótico, que os peixes precisam para a sua respiração. Que elemento é esse?", "Oxigênio", "Plantas", "Areia", "Luz", 1],]
]

