
# questions = [
#     ["Qual é a capital da França?", "Paris", "Londres", "Berlim", "Roma", 1],
#     ["Qual é o resultado de 8 + 5?", "12", "13", "15", "18", 2],
#     ["Quem pintou a Mona Lisa?", "Picasso", "Da Vinci", "Van Gogh", "Warhol", 2],
#     ["Quanto é 6 multiplicado por 7?", "36", "42", "48", "54", 2],
#     ["Qual é o maior planeta do sistema solar?", "Marte", "Saturno", "Júpiter", "Vênus", 3],
#     ["Quem escreveu a obra 'Dom Quixote'?", "Machado de Assis", "Miguel de Cervantes", "Jorge Luis Borges", "Gabriel García Márquez", 2],
#     ["Qual é a fórmula química da água?", "H2O", "CO2", "NaCl", "CH4", 1],
#     ["Quem foi o primeiro presidente dos Estados Unidos?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "John F. Kennedy", 1],
#     ["Qual é o resultado de 4 ao cubo?", "16", "32", "64", "128", 3],
#     ["Qual é a capital da Rússia?", "Moscou", "São Petersburgo", "Kiev", "Varsóvia", 1],
#     ["Quem descobriu a teoria da relatividade?", "Isaac Newton", "Galileu Galilei", "Albert Einstein", "Nikola Tesla", 3],
#     ["Qual é o símbolo químico do ouro?", "Au", "Ag", "Cu", "Fe", 1],
#     ["Quem foi o autor da obra 'Romeu e Julieta'?", "William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen", 1],
#     ["Qual é a capital do Brasil?", "Rio de Janeiro", "Brasília", "São Paulo", "Salvador", 2],
#     ["Qual é o resultado de 9 dividido por 3?", "1", "2", "3", "4", 3],
#     ["Quem pintou a obra 'A Noite Estrelada'?", "Leonardo da Vinci", "Michelangelo", "Salvador Dalí", "Vincent van Gogh", 4],
#     ["Qual é o maior oceano do mundo?", "Atlântico", "Índico", "Pacífico", "Ártico", 3],
#     ["Qual é o resultado de 2 elevado a 8?", "8", "16", "64", "256", 4],
#     ["Quem escreveu a obra '1984'?", "George Orwell", "Aldous Huxley", "Ernest Hemingway", "F. Scott Fitzgerald", 1],
#     ["Qual é o resultado de 15 menos 7?", "5", "6", "7", "8", 3],
#     ["Quem foi o pintor do quadro 'A Última Ceia'?", "Pablo Picasso", "Salvador Dalí", "Michelangelo", "Leonardo da Vinci", 4]

# ]
questions = [
    ["Qual o número entre 22 e 24", "28", "23", "46", "22",2],
    ["Qual a definição de números pares?", "Números com duas casas", "Números grandes", "Números divisíveis por 2", "Números que contém 2",3],
    ["Quanto é 22 dividido por 2", "2", "10", "11", "1",3],
    ["Qual é o formato que possuí apenas 3 lados", "Triângulo", "Quadrado", "Círculo", "Trapézio",1],
    ["Quanto é 25 dividido por 5?","15", "20", "10", "5",4],
    ["Quanto é 3 multiplicado por 4?", "7", "12", "4", "2", 2],
    ["Se dividirmos 8 bolos para quatro pessoas, cada um ganha quantos bolos? ?", "½ ", "2", "4", "1",2],
    ["Qual o nome da figura geométrica de  quatro lados", "Quadrilátero", "Círculo", "Triângulo", "Prisma",1],
    ["Quanto é 41 -26?", "20","15", "1", "0",2],
    ["Qual o nome da operação em que se diminui uma quantidade da outra?", "Adição", "Divisão", "Multiplicação", "Subtração",4],
    ["Qual o nome da operação  que consiste em somar o mesmo número várias vezes ?", "Subtração", "Divisão", "Adição", "Multiplicação",4],
    ["Qual o nome da operação em que se soma dois números?", "Adição", "Divisão", "Multiplicação", "Subtração",1],
    ["Qual destes não é um quadrilátero", "Trapézio", "Retângulo", "Pentágono", "Quadrado",3], 
    ["Qual o nome da figura geométrica sem nenhum lado", "Círculo", "Quadrado", "Triângulo", "Semi-círculo",1],
    ["Qual das seguintes sequências está em ordem crescente?", "2,1,3", "1,2,3", "3,1,2", "3,2,1",2],
    ["Qual das seguintes sequências está em ordem decrescente", "3,1,2", "2,1,3", "1,2,3", "3,2,1",4],
    ["Se tenho 6 amigos e quero dar 4 chocolates para cada, de quantos chocolates preciso?", "18", "6", "12", "24",4],
    ["Quantos sapatos 8 pessoas precisam para calçar todos os pés?", "8", "16", "10", "4",2],
    ["Se consigo fazer 2 desenhos com um lápis, de quantos lápis preciso no mínimo para fazer 11 desenhos ?", "6", "5", "3", "2",1],
    ["Em um jogo de celular consigo fazer 15 pontos em 10 minutos, quantos pontos faço em 30 minutos?", "20", "45", "35", "20",2],
    ["Quanto é 8x7?", "36", "49", "64", "56",4],
    ["Quanto é 10x10-23", "77", "67", "80", "0",1],
    ["Qual o maior número que é possível criar com os algarismos ‘7’, ‘9’, ‘3’, e ‘2’", "2973", "7923", "9732", "9237",3],
    ["Fui para uma lanchonete com 10 reais, comprei um salgado de 4 reais e um suco de 2 reais, quanto sobrou?", "4", "6", "10", "2",1],
    ["Qual dessas operações resulta em 52?", "18+12", "21-11", "4x30", "20+32",4],
    ["Qual dessas operações resulta em 100?", "49+51", "100/10", "100-1", "10+0",1],
    ["Qual dessas operações resulta em 27?", "16x1", "30-4", "27x1", "15+10",3],
    ["Qual dessas operações resulta em 0?", "3x5-10", "10+2", "35-20-15", "20/2",3],
    ["Qual dessas operações resulta em 70?","15x4", "10x10", "100-29", "35x2",4],
    ["Qual fração representa 0,25", "¼ ", "⅕ ", "⅙ ", "½ ",1],
    ["Represente  ¼ em número decimal", "0,1", "0,5", "0,1",  "0,25",4],
    ["Qual o resultado da soma dessas frações? ½+½ ", "1", "¼ ", "⅛ ", "½ ",1],
    ["Qual o resultado da soma dessas frações? ¼ +¼ ", "½ ", "1", "⅛ ", " ⅓ ",1],
    ["Qual número que subtraído por 3 resulta em 7?", "2", "10", "7", "4",2],
    ["Qual número que ao adicionar 4 resulta em 10?", "8", "5", "3", "6",4],
    ["Se um vídeogame custa 200 reais, quantos videogames posso comprar com 1000 reais?", "1", "3", "5", "10",3],
    ["Qual numero completa a seguinte sequência de números crescentes “1,2,?,4,5,6", "6", "4", "3", "8",3],
    ["Qual numero completa a seguinte sequência de números decrescentes ”6,5,4,3,?,1?", "1", "3", "4", "2",4],
    ["Se consigo fazer um bolo em 3 horas, quantos bolos consigo fazer em um dia?", "3", "6", "8", "2",3],
    ["Qual é o dobro do número 4 ?", "16", "5", "6",  "8",4],
    ["Qual é a metade do número 4 ?", "8", "2", "5",  "16",2],
    ["Preencha o número que falta na operação: 20 + ? = 26", "11", "3", "4", "6",4],
    ["Preencha o número que falta na operação: 52 - ? = 31", "21", "4", "9", "2", 1],
    ["Preencha o número que falta na operação: 8 - ? = 1", "7", "6", "2", "0",1],
    ["Preencha o número que falta na operação: 40 / ? = 4", "5", "4", "10", "2",3],
    ["Preencha o número que falta na operação: 5 x ? = 30", "10", "2", "1", "6",4],
    ["Qualquer número multiplicado por ? sempre resulta nele mesmo.", "4", "0", "1", "3",3],
    ["Qualquer número multiplicado por ? sempre resulta em zero", "3", "1", "0", "10",3],
    ["Quantas casas decimais existem no número 144?", "1", "2", "3", "4",3],
    ["Qual o nome da operação em que se reparte uma quantidade em porções menores iguais?", "Divisão", "Adição", "Multiplicação", "Subtração",1],
]
# Matemática_questions = [["Qual o número entre 22 e 24", "23", "28", "46", "22", 1],
#     ["Qual a definição de números pares?", "Números divisíveis por 2", "Números grandes", "Números com duas casas", "Números que contém 2", 1],
#     ["Quanto é 22 dividido por 2", "11", "10", "2", "1", 1],
#     ["Qual é o formato que possuí apenas e lados", "Triângulo", "Quadrado", "Círculo", "Trapézio", 2],
#     ["Quanto é 25 dividido por 5?", "5", "20", "10", "15", 3],
#     ["Quanto é 3 multiplicado por 4?", "12", "7", "4", "3", 1],
#     ["Qual o menor número de divisões de dois bolos para 4 pessoas?", "½ ", "2", "4", "1", 1],
#     ["Qual o nome do formato com quatro lados", "Quadrilátero", "Círculo", "Triângulo", "Prisma", 1],
#     ["Quanto é 41 -26?", "15", "20", "1", "0", 1],
#     ["Qual o nome da operação em que se diminui uma quantidade da outra?", "Subtração", "Divisão", "Multiplicação", "Adição", 1],
#     ["Qual o nome da operação em que se reparte uma quantidade em porções menores iguais?", "Divisão", "Adição", "Multiplicação", "Subtração", 1],
#     ["Qual o nome da operação em que consistem em várias adições sucessivas de conjuntos?", "Multiplicação", "Divisão", "Adição", "Subtração", 1],
#     ["Qual o nome da operação em que se junta dois conjuntos?", "Adição", "Divisão", "Multiplicação", "Subtração", 1],
#     ["Qual destes não é um quadrilátero", "Pentágono", "Retângulo", "Trapézio", "Quadrado", 1],
#     ["Qual o nome do formato sem nenhum lado", "Círculo", "Quadrado", "Triângulo", "Semi-círculo", 1],
#     ["Qual das seguintes sequências está em ordem crescente?", "1,2,3", "2,1,3", "3,1,2", "3,2,1", 1],
#     ["Qual das seguintes sequências está em ordem decrescente", "3,2,1", "2,1,3", "1,2,3", "3,1,2", 1],
#     ["Se tenho 6 amigos e quero dar 4 chocolates para cada, de quantos chocolates preciso?", "24", "6", "12", "18", 1],
#     ["Quantos sapatos 8 pessoas precisam para calçar todos os pés?", "16", "8", "10", "4", 1],
#     ["Se consigo fazer 2 desenhos com um lápis, de quantos lápis preciso no mínimo para fazer 11 desenhos ?", "6", "5", "3", "2", 1],
#     ["Em um jogo de celular consigo fazer 15 pontos em 10 minutos, quantos pontos fiz em 30 minutos?", "45", "30", "35", "20", 1],
#     ["Quanto é 8x7?", "56", "49", "64", "36", 1],
#     ["Quanto é 10x10-23", "77", "67", "80", "0", 1],
#     ["Qual o maior número que é possível criar com os algarismos ‘7’, ‘9’, ‘3’, e ‘2’", "9732", "7923", "2973", "9237", 1],
#     ["Fui para uma lanchonete com 10 reais, comprei um salgado de 4 reais e um suco de 2 reais, quanto sobrou?", "4", "6", "10", "2", 1],
#     [""]
# ]
# Matemática_questions = ["Qual o número entre 22 e 24", ["23", "28", "46", "22"]],
#     ["Qual a definição de números pares?", ["Números divisíveis por 2", "Números grandes", "Números com duas casas", "Números que contém 2"]],
#     ["Quanto é 22 dividido por 2", ["11", "10", "2", "1"]],
#     ["Qual é o formato que possuí apenas e lados", ["Triângulo", "Quadrado", "Círculo", "Trapézio"]],
#     ["Quanto é 25 dividido por 5?", ["5", "20", "10", "15"]],
#     ["Quanto é 3 multiplicado por 4?", ["12", "7", "4", "3"]],
#     ["Qual o menor número de divisões de dois bolos para 4 pessoas?", ["½ ", "2", "4", "1"]],
#     ["Qual o nome do formato com quatro lados", ["Quadrilátero", "Círculo", "Triângulo", "Prisma"]],
#     ["Quanto é 41 -26?", ["15", "20", "1", "0"]],
#     ["Qual o nome da operação em que se diminui uma quantidade da outra?", ["Subtração", "Divisão", "Multiplicação", "Adição"]],
#     ["Qual o nome da operação em que se reparte uma quantidade em porções menores iguais?", [“Divisão", "Adição", "Multiplicação", "Subtração"]],
#     ["Qual o nome da operação em que consistem em várias adições sucessivas de conjuntos?", ["Multiplicação", "Divisão", "Adição", "Subtração"]],
#     ["Qual o nome da operação em que se junta dois conjuntos?", ["Adição", "Divisão", "Multiplicação", "Subtração"]],
#    ["Qual destes não é um quadrilátero", ["Pentágono", "Retângulo", "Trapézio", "Quadrado"]],
#    ["Qual o nome do formato sem nenhum lado", ["Círculo", "Quadrado", "Triângulo", "Semi-círculo"]],
#    ["Qual das seguintes sequências está em ordem crescente?", ["1,2,3", "2,1,3", "3,1,2", "3,2,1"]],
#    ["Qual das seguintes sequências está em ordem decrescente", ["3,2,1", "2,1,3", "1,2,3", "3,1,2"]],
#    ["Se tenho 6 amigos e quero dar 4 chocolates para cada, de quantos chocolates preciso?", ["24", "6", "12", "18"]],
#    ["Quantos sapatos 8 pessoas precisam para calçar todos os pés?", ["16", "8", "10", "4"]],
#    ["Se consigo fazer 2 desenhos com um lápis, de quantos lápis preciso no mínimo para fazer 11 desenhos ?", ["6", "5", "3", "2"]],
#    ["Em um jogo de celular consigo fazer 15 pontos em 10 minutos, quantos pontos fiz em 30 minutos?", ["45", "30", "35", "20"]],
#    ["Quanto é 8x7?", ["56", "49", "64", "36"]],
#    ["Quanto é 10x10-23", ["77", "67", "80", "0"]],
# ["Qual o maior número que é possível criar com os algarismos ‘7’, ‘9’, ‘3’, e ‘2’", ["9732", "7923", "2973", "9237"]],
# ["Fui para uma lanchonete com 10 reais, comprei um salgado de 4 reais e um suco de 2 reais, quanto sobrou?", ["4", "6", "10", "2"]],
# ["Qual dessas operações resulta em 52?", ["20+32", "21-11", "4x30", "18+12]],
# ["Qual dessas operações resulta em 100?", ["1000/10", "41+50", "100-1", "10+0"]],
# ["Qual dessas operações resulta em 27?", ["27x1", "30-4", "12+6", "15+10"]],
# ["Qual dessas operações resulta em 0?", ["35-20-15", "10+2", "3x5-10", "20/2"]],
# ["Qual dessas operações resulta em 70?", ["35x2", "10x10", "100-29", "15x4"]],
# ["Represente 0,25 em fração", ["¼ ", "⅕ ", "⅙ ", "½ "]],
# ["Represente  ¼ em número decimal", ["0,25", "0,5", "0,1", "0,2"]],
# ["Qual o resultado da soma dessas frações? ½+½ ", ["1", "¼ ", "⅛ ", "½ "]],
# ["Qual o resultado da soma dessas frações? ¼ +¼ ", ["½ ", "1", "⅛ ", " ⅓  "]],
# ["Qual número que subtraído por 3 resulta em 7?", ["10", "3", "7", "4"]],
# ["Qual número que ao adicionar 4 resulta em 10?", ["6", "5", "3", "8"]],
# ["Se um vídeo custa 200 reais, quantos videogames posso comprar com 1000 reais?", ["5", "3", "1", "10"]],
# ["Qual numero completa a seguinte sequência de números crescentes “1,2,?,4,5,6", ["3", "4", "6", "8"]],
# ["Qual numero completa a seguinte sequência de números decrescentes ”6,5,4,3,?,1?", ["2", "3", "4", "1"]],
# ["Se consigo fazer um bolo em 3 horas, quantos bolos consigo fazer em um dia?", ["8", "6", "3", "2"]],
# ["Qual é o dobro do número 4 ?", ["8", "5", "6", "16"]],
# ["Qual é a metade do número 4 ?", ["2", "8", "5", "16"]],
# ["Preencha o número que falta na operação: 20 + ? = 26", ["6", "3", "4", "11"]],
# ["Preencha o número que falta na operação: 52 - ? = 31", ["21", "4", "9", "3"]],
# ["Preencha o número que falta na operação: 8 - ? = 1", ["7", "6", "2", "0"]],
# ["Preencha o número que falta na operação: 40 / ? = 4", ["10", "4", "5", "2"]],
# ["Preencha o número que falta na operação: 5 x ? = 30", ["6", "2", "1", "10"]],
# ["Qualquer número multiplicado por ? sempre resulta nele mesmo.", ["1", "0", "4", "3"]],
# ["Qualquer número multiplicado por ? sempre resulta em zero", ["0", "1", "2", "10"]],
# ["Quantas casas decimais existem no número 144?", ["3", "2", "1", "4"]],
# ]